name: Continuous Deployment
on:
  push:
    branches: ['main']

  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            source ~/.nvm/nvm.sh || true
            nvm use 20 || true
            cd /home/farhan/apps/tabungan-wisata || true
            git stash || true
            git pull origin main || true
            pnpm install || true
            pnpm run build || true
            cd apps/front || true
            NODE_ENV=production pm2 reload tw-front --update-env || true
            cd ../student || true
            NODE_ENV=production pm2 reload tw-student --update-env || true
            cd ../admin || true
            NODE_ENV=production pm2 reload tw-admin --update-env || true
